---
title: "PrediXcan_paper_plots"
author: "Heather E. Wheeler"
date: "`r Sys.time()`"
output: 
  html_document:
    pandoc_args: [
      "+RTS", "-K64m",
      "-RTS"
    ]
---


```{r,DGNtoGEU,fig.height=4,fig.width=4}
date <- Sys.Date()
"%&%" = function(a,b) paste(a,b,sep="")
library(ggplot2)
library(dplyr)
library(tidyr)
library(reshape2)
qqR2 <- function(corvec,nn)
{
  set.seed(12345)
## nn is the sample size, number of individuals used to compute correlation.
## needs correlation vector as input.
## nullcorvec generates a random sample from correlation distributions, under the null hypothesis of 0 correlation using Fisher's approximation.
  mm <- length(corvec)
  nullcorvec = tanh(rnorm(mm)/sqrt(nn-3)) ## null correlation vector
  qqplot(nullcorvec^2,corvec^2, xlab=expression("Expected R"^"2"), ylab=expression("Observed R"^"2"),ylim=c(0,0.825),cex=0.5); abline(0,1); grid()
  data<-data.frame(cbind(sort(corvec^2),sort(nullcorvec^2)))
  colnames(data)<-c("obs","exp")
  return(data)
}

obs<-read.table('/Users/heather/Dropbox/PrediXcan/GEUVADIS/observed',header=T)
rownames(obs)<-obs[,1]
obs<-obs[,-1]
pred<-read.table('/Users/heather/Dropbox/PrediXcan/GEUVADIS/DGN.WB.predicted.txt',skip=1)
headpred<-scan('/Users/heather/Dropbox/PrediXcan/GEUVADIS/header.DGN.WB.predicted.txt','character')
colnames(pred)<-headpred
rownames(pred)<-pred[,1]
pred<-pred[,-1]
tpred<-as.data.frame(t(pred))

commonIDs<-intersect(rownames(tpred),rownames(obs))
newpred<-tpred[commonIDs,]

genelist<-intersect(colnames(newpred),colnames(obs))

resultsmat <- matrix(0,ncol=2,nrow=length(genelist))
colnames(resultsmat) <- c('R2','p')
rownames(resultsmat) <- genelist

for(i in 1:length(genelist)){
  gene<-genelist[i]
  res<-cor.test(obs[,gene],newpred[,gene])
  info<-c(res$estimate^2,res$p.value)
  resultsmat[i,]<-info
}

finalres<-resultsmat[order(resultsmat[,1],decreasing=T),]
write.table(finalres,file="train.DGN-WB_test.GEUVADIS_R2.txt",quote=F)

p<-qqR2(sqrt(finalres[,1]),length(commonIDs))
```

```{r,geuvadis_h2_to_OoS_R2}
source('multiplot.R')
geuR2<-read.table('/Users/heather/GitHub/PrediXmod/Paper_plots/train.DGN-WB_test.GEUVADIS_R2.txt',header=T)
geuh2<-read.table('/Users/heather/Dropbox/PrediXcan/GEUVADIS/GEUVADIS.EUR.localGRM.h2.exp.2014-08-13.txt',header=T)

geuR2<-geuR2 %>% mutate(gene=rownames(geuR2))

all<-inner_join(geuh2,geuR2,by='gene')
all<-all %>% mutate(ymin = pmax(0, h2 - 2 * se), ymax = pmin(1, h2 + 2 * se)) %>% arrange(h2)

h2plot<-ggplot(all,aes(x=1:nrow(all),y=h2,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point()+coord_cartesian(ylim=c(-0.05,0.85))
h2plot<- h2plot + geom_point(data=all,aes(x=1:nrow(all),y=R2),color='green',cex=1) + xlab(expression("Genes sorted by h"^2)) + ylab(expression(h^{2} ~"(black) or " ~ R^{2} ~ "(green)")) +theme_bw(30)
h2plot

qqR2plot<-ggplot(p,aes(x=exp,y=obs))+geom_point(pch=1,cex=1.5)+coord_cartesian(ylim=c(-0.05,0.85))
qqR2plot<- qqR2plot + geom_abline(intercept=0, slope=1) + xlab(expression("Expected R"^2)) + ylab(expression("Observed Predictive R"^2)) + theme_bw(30)
qqR2plot


png(file="DGN_to_GEU_qqR2_R2h2.png",height=480,width=960)
multiplot(qqR2plot,h2plot,cols=2)
dev.off()

tiff(file="DGN_to_GEU_qqR2_R2h2.tiff",height=480,width=960)
multiplot(qqR2plot,h2plot,cols=2)
dev.off()

```


```{r,PritchardtoGEU,fig.height=4,fig.width=4}
pritch<-read.table('/Users/heather/Dropbox/PrediXcan/GEUVADIS/Pritchard/Geneexpsubset',header=T)
geu<-read.table('/Users/heather/Dropbox/PrediXcan/GEUVADIS/Pritchard/GeuvadiswithPritchardgenes_individuals',header=T)

genelist <- intersect(rownames(pritch),rownames(geu))
resultsmat <- matrix(0,ncol=2,nrow=length(genelist))
colnames(resultsmat) <- c('R2','p')
rownames(resultsmat) <- genelist

for(i in 1:length(genelist)){
  gene<-genelist[i]
  res<-cor.test(as.numeric(pritch[gene,]),as.numeric(geu[gene,]))
  info<-c(res$estimate^2,res$p.value)
  resultsmat[i,]<-info
}

finalres2<-resultsmat[order(resultsmat[,1],decreasing=T),]
write.table(finalres2,file="compareExp.Pritchard_GEUVADIS_R2.txt",quote=F)

p<-qqR2(sqrt(finalres2[,1]),dim(pritch)[2])

tiff("Fig3.GEU.qqR2.tiff",width=960,height=480,res=125)
par(mfcol=c(1,2))
qqR2(sqrt(finalres[,1]),length(commonIDs))
qqR2(sqrt(finalres2[,1]),dim(pritch)[2])
dev.off()

png("Fig3.GEU.qqR2.png",width=960,height=480,res=125)
par(mfcol=c(1,2))
qqR2(sqrt(finalres[,1]),length(commonIDs))
qqR2(sqrt(finalres2[,1]),dim(pritch)[2])
dev.off()
```

```{r, pred_v_rep}
pred <- data.frame(finalres) %>% mutate(gene=rownames(finalres))

repgene<-scan('/Users/heather/Dropbox/PrediXcan/GEUVADIS/Pritchard/Geneexpsubset.GENE.list', 'character')
rep <- data.frame(resultsmat) %>% mutate(gene=repgene)

all <- inner_join(pred,rep,by='gene')
dim(all)

p<-ggplot(all,aes(x=R2.x,y=R2.y)) +geom_point(cex=0.8) + geom_smooth(method = "lm")
p1<-p + xlab(expression("PrediXcan R"^"2")) + ylab(expression("RNA-seq replication R"^"2")) + theme_bw(10) + coord_cartesian(xlim=c(0,0.85),ylim=c(0,0.85))
print(p1)

png("pred_v_rep_LCLs.png",width=480,height=480,res=125)
print(p1)
dev.off()

##correlation b/t replication R2 and PrediXcan R2
summary(lm(R2.y~R2.x,all))

##plot sorted R2's
sortpred<-sort(all$R2.x)
sortrep<-sort(all$R2.y)
sorted<-data.frame(cbind(sortpred,sortrep))
p<-ggplot(sorted,aes(x=sortpred,y=sortrep)) +geom_point(cex=0.8) + geom_abline(intercept=0, slope=1,color='red')
p1<-p + xlab(expression("sorted PrediXcan R"^"2")) + ylab(expression("sorted RNA-seq replication R"^"2")) + theme_bw(10) + coord_cartesian(xlim=c(0,0.85),ylim=c(0,0.85))
print(p1)

png("sorted_pred_v_rep_LCLs.png",width=480,height=480,res=125)
print(p1)
dev.off()

forbp<-all %>% select(R2.x,R2.y)
colnames(forbp) <- c("PrediXcan_Imputed","RNA_Replicate")
forbp<-melt(forbp)
p <- ggplot(forbp, aes(x = variable, y = value))
p1 <- p + geom_boxplot() +  ylab(expression("R"^2)) + xlab("GEUVADIS comparison") + theme_bw(10)
print(p1)

png("boxplot_pred_v_rep_LCLs.png",width=480,height=720,res=125)
print(p1)
dev.off()
```

```{r,DGNtoGEUexamples,fig.height=4,fig.width=4}
##top predictions
head(finalres)
obsexp <-obs %>% select(ERAP2,LDHC,RPS26,NUDT2) 
obsexp <- gather(obsexp)

predexp <- newpred %>% select(ERAP2,LDHC,RPS26,NUDT2)
predexp <- gather(predexp)

data <- cbind(obsexp,predexp)
colnames(data) <- c("gene","Observed","key","Predicted")
p<-ggplot(data,aes(x=Predicted,y=Observed)) +geom_point(cex=0.8)+facet_wrap(~gene,scales="free",ncol=2)+ geom_smooth(method = "lm")
p1<-p + xlab("Predicted Expression") + ylab("Observed Expression") + theme_bw(20)
print(p1)

tiff("Fig4.DGNtoGEU.examples.tiff",width=960,height=960,res=125)
print(p1)
dev.off()

png("Fig4.DGNtoGEU.examples.png",width=960,height=960,res=125)
print(p1)
dev.off()
```

```{r,dgn_to_gtex}
qqR2 <- function(corvec,nn,tissue)
{
  set.seed(12345)
## nn is the sample size, number of individuals used to compute correlation.
## needs correlation vector as input.
## nullcorvec generates a random sample from correlation distributions, under the null hypothesis of 0 correlation using Fisher's approximation.
  mm <- length(corvec)
  nullcorvec = tanh(rnorm(mm)/sqrt(nn-3)) ## null correlation vector
  data<-data.frame(cbind(sort(corvec^2),sort(nullcorvec^2)))
  data <- data %>% mutate(tissue=tissue)
  colnames(data)<-c("obs","exp","tissue")
  return(data)
}

tissueinfo<-read.table('/Users/heather/GitHub/PrediXmod/Paper_plots/GTEx_pilot_sample_sizes.txt')

finalp<-data.frame()

for(i in 1:dim(tissueinfo)[1]){
  tis<-as.character(tissueinfo[i,1])
  n<-tissueinfo[i,2]
  resfile<-'/Users/heather/GitHub/PrediXmod/Paper_plots/train.DGN-WB_test.GTEX_' %&% tis %&% '_R2.txt'
  finalres<-read.table(resfile,header=T)
  p<-qqR2(sqrt(finalres[,1]),n,tis)
  finalp<-rbind(finalp,p)
}

plot<-ggplot(finalp,aes(x=exp,y=obs))+geom_point(pch=1,cex=1.5)+facet_wrap(~tissue,scales="fixed",ncol=3)
p2<- plot + geom_abline(intercept=0, slope=1) + xlab(expression("Expected R"^2)) + ylab(expression("Observed Predictive R"^2)) + theme_bw(20)
p2

tiff(file="DGN-EN_to_GTEx-pilot.tiff",height=720,width=720)
p2
dev.off()

png(file="DGN-EN_to_GTEx-pilot.png",height=720,width=720)
p2
dev.off()

```

